### ISSUE TITLE
Undefined error in 9bda16809c1e4e887e5efa99c838a30591e9cc7c

### ISSUE THREAD

**Issue by zabc995** [zabc995/WebMyPhamPHP#1]
Now me have a Error in  9bda16809c1e4e887e5efa99c838a30591e9cc7c commit.

Please give me solution @nonormal

**Comment by nonormal** [comment]
Ok i see. You should remove this error folder and assign task for me.

**Comment by zabc995** [comment]
674586251309d54ac63a3509ed138a5a75f2a294 okay, i'm remove it. Plz help me fix it

**Comment by nonormal** [comment]
This error fixed 83b3c24932620d06e51955b28739d7419eca76c2

Close Issue now @zabc995
